networks:
  diary:
    attachable: true
    name: diary

volumes:
  pgdata:

services:
  nginx:
    container_name: "diary-nginx"
    image: "nginx:mainline-alpine"
    networks:
      - diary
    ports:
      - 10000:80
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./nginx/htpasswd:/etc/nginx/htpasswd:ro"
      - "./www:/data:ro"
    restart: always

  node:
    container_name: "diary-node"
    image: "node:22-alpine"
    command: sh -c "cd /app && node src/main.mjs"
    init: true
    networks:
      - diary
    volumes:
      - "./:/app:ro"
    restart: always
    environment:
      POSTGRES_HOST: "diary-postgres"
      POSTGRES_PORT: 5432
      POSTGRES_USER: diary
      POSTGRES_PASSWORD: diary
      POSTGRES_DB: diary
    depends_on:
      - postgres

  postgres:
    container_name: "diary-postgres"
    image: "postgres:17-alpine"
    networks:
      - diary
    ports:
      - 10001:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: diary
      POSTGRES_PASSWORD: diary
